# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspace/PracticeProblems

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspace

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspace/CMakeFiles /workspace//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspace/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PracticeProblems

# Build rule for target.
PracticeProblems: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PracticeProblems
.PHONY : PracticeProblems

# fast build rule for target.
PracticeProblems/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PracticeProblems.dir/build.make CMakeFiles/PracticeProblems.dir/build
.PHONY : PracticeProblems/fast

# target to build an object file
Arrays/Source/FindLargestElement.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PracticeProblems.dir/build.make CMakeFiles/PracticeProblems.dir/Arrays/Source/FindLargestElement.o
.PHONY : Arrays/Source/FindLargestElement.o

# target to preprocess a source file
Arrays/Source/FindLargestElement.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PracticeProblems.dir/build.make CMakeFiles/PracticeProblems.dir/Arrays/Source/FindLargestElement.i
.PHONY : Arrays/Source/FindLargestElement.i

# target to generate assembly for a file
Arrays/Source/FindLargestElement.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PracticeProblems.dir/build.make CMakeFiles/PracticeProblems.dir/Arrays/Source/FindLargestElement.s
.PHONY : Arrays/Source/FindLargestElement.s

# target to build an object file
Pointers/Source/001TypesOfPointers.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PracticeProblems.dir/build.make CMakeFiles/PracticeProblems.dir/Pointers/Source/001TypesOfPointers.o
.PHONY : Pointers/Source/001TypesOfPointers.o

# target to preprocess a source file
Pointers/Source/001TypesOfPointers.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PracticeProblems.dir/build.make CMakeFiles/PracticeProblems.dir/Pointers/Source/001TypesOfPointers.i
.PHONY : Pointers/Source/001TypesOfPointers.i

# target to generate assembly for a file
Pointers/Source/001TypesOfPointers.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PracticeProblems.dir/build.make CMakeFiles/PracticeProblems.dir/Pointers/Source/001TypesOfPointers.s
.PHONY : Pointers/Source/001TypesOfPointers.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... PracticeProblems"
	@echo "... Arrays/Source/FindLargestElement.o"
	@echo "... Arrays/Source/FindLargestElement.i"
	@echo "... Arrays/Source/FindLargestElement.s"
	@echo "... Pointers/Source/001TypesOfPointers.o"
	@echo "... Pointers/Source/001TypesOfPointers.i"
	@echo "... Pointers/Source/001TypesOfPointers.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

